# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - allegro_hand_controller

  allegro_hand_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_12
      - joint_13
      - joint_14
      - joint_15
      - joint_4
      - joint_5
      - joint_6
      - joint_7
      - joint_8
      - joint_9
      - joint_10
      - joint_11
    action_ns: follow_joint_trajectory
    default: true