# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    allegro_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    index_tip_controller:
      type: position_controllers/GripperActionController


    thumb_tip_controller:
      type: position_controllers/GripperActionController


    middle_tip_controller:
      type: position_controllers/GripperActionController


    ring_tip_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

allegro_hand_controller:
  ros__parameters:
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_12
      - joint_13
      - joint_14
      - joint_15
      - joint_4
      - joint_5
      - joint_6
      - joint_7
      - joint_8
      - joint_9
      - joint_10
      - joint_11
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
index_tip_controller:
  ros__parameters:
    joints:
      []
thumb_tip_controller:
  ros__parameters:
    joints:
      []
middle_tip_controller:
  ros__parameters:
    joints:
      []
ring_tip_controller:
  ros__parameters:
    joints:
      []


      